# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import djplaces.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170110_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=djplaces.fields.LocationField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
