# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 16:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170111_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estimated_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='value £'),
        ),
    ]
