# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 19:57
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170118_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category', verbose_name='Filter by category'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='distance',
            field=models.FloatField(null=True, verbose_name='Distance (miles)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='app.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='estimated_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Value £'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_rental_period',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Min. days'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.CharField(max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price £/day'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
