# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:11
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_item_email_sent_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='place',
        ),
        migrations.AlterField(
            model_name='item',
            name='estimated_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Value (£)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price (£/day)'),
        ),
    ]
